name: nearby_service_example_full
description: Demonstrates how to use the nearby_service plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  provider: ^6.1.1
  file_picker: ^10.0.0
  flutter:
    sdk: flutter

  nearby_service:
    path: ../
  path_provider: ^2.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
